<?php

namespace AppBundle\Repository;

/**
 * DummyPlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DummyPlayerRepository extends \Doctrine\ORM\EntityRepository
{
}
