security:

    providers:
        in_memory:
            memory: ~

        db_provider:
            entity:
                class: AppBundle:AuthUser
                property: username

    firewalls:
        main:
            provider: db_provider
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: postLogin
                always_use_default_target_path: true
            logout:
                path: logout
                invalidate_session: true
                target: login

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/(es|en)/public, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(es|en)/email, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(es|en)/web, roles: [ROLE_USER, ROLE_ADMIN, ROLE_STAFF] }

    encoders:
        AppBundle\Entity\AuthUser: bcrypt